services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend_app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend_app:/app
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./frontend_app:/app
      - /app/node_modules
    # environment:
    #   - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
