name: "Create Azure PostgreSQL Server"
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - create_pipline
permissions:
  id-token: write
  contents: read
jobs:
  create_postgres_server:
    name: Creating PostgreSQL Server
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Create PostgreSQL Server
        run: |
          IP=$(curl -s https://ifconfig.me)
          echo "Runner Public IP: $IP"
          az postgres flexible-server create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ vars.AZURE_POSTGRESQL_SERVER_NAME }} \
            --location ${{ vars.AZURE_LOCATION }} \
            --admin-user ${{ secrets.AZURE_POSTGRESQL_ADMIN_USER }} \
            --admin-password ${{ secrets.AZURE_POSTGRESQL_ADMIN_PASSWORD }} \
            --tier Burstable \
            --sku-name Standard_B1ms \
            --version 16 \
            --public-access $IP
