Create Azure PostgreSQL Server Pipeline

name: Create Azure PostgreSQL Server
on:
  workflow_dispatch:
  # schedule:
  #   # - cron: '0 0 * * *'  # Runs daily at midnight 
  push:
    branches:
      - main
      - create_pipline   #  Додано для запуску з гілки feature/pipelines, видалити у фінальній версії
jobs:
  create_postgres_server:
  name  Creating PostgreSQL Server
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   # uses: actions/checkout@v2

      # - name: Set up Azure CLI
      #   # uses: azure/setup-azure-cli@v1

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Create PostgreSQL Server
        run: |
          az postgres flexible-server create \
            --resource-group ${{ secret.AZURE_RESOURCE_GROUP }} \
            --name ${{ vars.AZURE_POSTGRESQL_SERVER_NAME }} \
            --location ${{ vars.AZURE_LOCATION }} \
            --admin-user ${{ secret.AZURE_POSTGRESQL_ADMIN_USER }} \
            --admin-password ${{ secret.AZURE_POSTGRESQL_ADMIN_PASSWORD }} \
            --sku-name GP_Standard_D2s_v3 \
            --version 13
      