name: "[PR] Verification pipeline"

on:
  pull_request:
    branches:
      - main
jobs:
  pytest:
    name: Running pytests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Running test
        run: |
          pip install pytest
          pytest -v
