name: "[PR] Verification pipeline"

on:
  pull_request:
    branches:
      - main
jobs:
  pytest:
    name: Running pytests on Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: instal libraries
        run: |
          pip install -r backend_app/requirements.txt
      - name: Running backend tests
        run: |
          pytest -v
  vitest:
    name: Running vitest on Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: instal libraries
        run: |
          cd frontend_app/
          npm install
      - name: Running frontend tests
        env:
          VITE_BACKEND_API_URL: "http://localhost:8000"
        run: |
          cd frontend_app/
          npm run test
